name: Daily Commit

on:
  schedule:
    - cron: '5 0 * * *' # Runs every day at 12:05 AM UTC
  workflow_dispatch: # Optional: Allows manual run

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit by 24f3003609@ds.study.iitm.ac.in
        run: |
          echo "Update at $(date)" >> daily_log.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add daily_log.txt
          git commit -m "Daily update"
          git push
